<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFrameworks>$(PrimaryTarget)</TargetFrameworks>
		<RootNamespace>Lab.Model</RootNamespace>
		<AssemblyName>Lab.Model</AssemblyName>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<!-- Assembly properties -->
	<PropertyGroup>
		<Authors>P Ryland</Authors>
		<Company>Rylogic</Company>
		<Description>Signal analysis laboratory - data and model layer.</Description>
		<Copyright>Copyright (c) Rylogic 2026</Copyright>
		<PackageLicenseUrl>https://opensource.org/licenses/MIT</PackageLicenseUrl>
		<Version>1.0.0</Version>
		<FileVersion>1.0.0</FileVersion>
		<AssemblyVersion>1.0.0</AssemblyVersion>
	</PropertyGroup>

	<!-- References -->
	<ItemGroup>
		<ProjectReference Include="$(RylogicRoot)projects\rylogic\Rylogic.Core\Rylogic.Core.csproj" />
		<ProjectReference Include="$(RylogicRoot)projects\rylogic\Rylogic.DB\Rylogic.DB.csproj" />
		<ProjectReference Include="$(RylogicRoot)projects\apps\CoinFlip\ExchApi.Common\ExchApi.Common.csproj" />
		<ProjectReference Include="$(RylogicRoot)projects\apps\CoinFlip\ExchApi.Binance\ExchApi.Binance.csproj" />
	</ItemGroup>

</Project>
