using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Rylogic.LDrawVisualiser.Core
{
	/// <summary>Info about a script file displayed in the scripts list</summary>
	public class ScriptInfo
	{
		public ScriptInfo(string filepath)
		{
			FilePath = filepath;
			Name = Path.GetFileNameWithoutExtension(filepath);
		}

		public string Name { get; }
		public string FilePath { get; }

		public override string ToString() => Name;
	}

	/// <summary>
	/// Manages the scripts directory. Scripts are .csx (C# script) files.
	/// A shared _init.csx provides #r directives so that VS gives IntelliSense
	/// without users needing to write #r lines in every script.
	/// </summary>
	public class ScriptProjectManager
	{
		private readonly LDrawVisualiserOptions m_options;

		public ScriptProjectManager(LDrawVisualiserOptions options)
		{
			m_options = options;
		}

		/// <summary>The scripts directory</summary>
		public string ScriptsDirectory => m_options.ScriptsDirectory;

		/// <summary>Path to the auto-generated LDrawVisualiser.csx</summary>
		public string InitScriptPath => Path.Combine(ScriptsDirectory, "LDrawVisualiser.csx");

		/// <summary>Ensure the scripts directory and _init.csx exist</summary>
		public void EnsureDirectoryExists()
		{
			Directory.CreateDirectory(ScriptsDirectory);
			GenerateInitScript();
		}

		/// <summary>Regenerate LDrawVisualiser.csx (call when assembly options change)</summary>
		public void GenerateInitScript()
		{
			var sb = new StringBuilder();
			sb.AppendLine("// Auto-generated by LDraw Visualiser. Do not edit.");
			sb.AppendLine("// Assembly references for IntelliSense support.");
			sb.AppendLine();

			// Extension directory assemblies (Rylogic.Core, Rylogic.Gfx)
			var ext_dir = Path.GetDirectoryName(typeof(ScriptProjectManager).Assembly.Location) ?? "";
			foreach (var dll in new[] { "Rylogic.Core.dll", "Rylogic.Gfx.dll" })
			{
				var dll_path = Path.Combine(ext_dir, dll);
				if (File.Exists(dll_path))
					sb.AppendLine($"#r \"{dll_path}\"");
			}

			// User-specified additional assemblies from options
			foreach (var asm in m_options.Assemblies)
			{
				if (File.Exists(asm))
					sb.AppendLine($"#r \"{asm}\"");
			}

			try { File.WriteAllText(InitScriptPath, sb.ToString()); }
			catch { /* Silently ignore write failures */ }
		}

		/// <summary>Get all user script files (excludes LDrawVisualiser.csx)</summary>
		public List<ScriptInfo> GetScripts()
		{
			if (!Directory.Exists(ScriptsDirectory))
				return new List<ScriptInfo>();

			return Directory.GetFiles(ScriptsDirectory, "*.csx")
				.Where(f => !string.Equals(Path.GetFileName(f), "LDrawVisualiser.csx", StringComparison.OrdinalIgnoreCase))
				.OrderBy(f => Path.GetFileNameWithoutExtension(f))
				.Select(f => new ScriptInfo(f))
				.ToList();
		}

		/// <summary>Create a new script file with the default template</summary>
		public ScriptInfo CreateScript(string name)
		{
			EnsureDirectoryExists();
			var filepath = Path.Combine(ScriptsDirectory, $"{name}.csx");
			File.WriteAllText(filepath, m_options.DefaultScriptText);
			return new ScriptInfo(filepath);
		}

		/// <summary>Delete a script file</summary>
		public void DeleteScript(ScriptInfo script)
		{
			if (File.Exists(script.FilePath))
				File.Delete(script.FilePath);
		}

		/// <summary>
		/// Read the script file and extract the script body
		/// (everything after #load, #r, and using directives).
		/// </summary>
		public string ReadScriptBody(ScriptInfo script)
		{
			if (!File.Exists(script.FilePath))
				return m_options.DefaultScriptText;

			try
			{
				var content = File.ReadAllText(script.FilePath);
				return ExtractScriptBody(content);
			}
			catch
			{
				return m_options.DefaultScriptText;
			}
		}

		/// <summary>Read the using directives from a script file</summary>
		public List<string> ReadUsingDirectives(ScriptInfo script)
		{
			if (!File.Exists(script.FilePath))
				return new List<string>();

			try
			{
				return File.ReadAllLines(script.FilePath)
					.Where(line => line.TrimStart().StartsWith("using ") && !line.TrimStart().StartsWith("using ("))
					.Select(line => line.Trim().TrimEnd(';'))
					.ToList();
			}
			catch
			{
				return new List<string>();
			}
		}

		/// <summary>Generate the .csx file content for a new script</summary>
		public string GenerateScriptContent(string body)
		{
			var sb = new StringBuilder();
			sb.AppendLine("#load \"_init.csx\"");
			sb.AppendLine();
			sb.AppendLine("using Rylogic.LDraw;");
			sb.AppendLine("using Rylogic.Maths;");
			sb.AppendLine();
			sb.AppendLine("// Script body \u2014 this code runs inside: string Generate(dynamic vars) { ... }");
			sb.Append(body);
			sb.AppendLine();
			return sb.ToString();
		}

		/// <summary>Extract the script body (strip #load, #r, using, and leading comments)</summary>
		private static string ExtractScriptBody(string content)
		{
			var lines = content.Split('\n');
			var body_lines = new List<string>();
			var in_body = false;

			foreach (var raw_line in lines)
			{
				var line = raw_line.TrimEnd('\r');
				var trimmed = line.TrimStart();

				if (!in_body)
				{
					// Skip directives, using statements, and blank/comment lines before the body
					if (trimmed.StartsWith("#load ") || trimmed.StartsWith("#r ") || trimmed.StartsWith("#r\""))
						continue;
					if (trimmed.StartsWith("using ") && !trimmed.StartsWith("using ("))
						continue;
					if (trimmed.StartsWith("//") || trimmed.Length == 0)
						continue;

					in_body = true;
				}

				if (in_body)
					body_lines.Add(line);
			}

			// Trim trailing empty lines
			while (body_lines.Count > 0 && string.IsNullOrWhiteSpace(body_lines[body_lines.Count - 1]))
				body_lines.RemoveAt(body_lines.Count - 1);

			return string.Join("\n", body_lines);
		}
	}
}