// Opt-in far-clip-fade output variants of the stock multi-UV PBR entry points. Simple-material and TEXCOORD_0 PBR variants are generated by
// 'forward_pixel.hlsli' and 'forward_pixel_pbr.hlsli'.
#include "view3d-12/src/shaders/hlsl/forward/forward.hlsl"
#include "view3d-12/src/shaders/hlsl/forward/far_clip_fade.hlsli"

// Preserve depth-writing multi-UV PBR coverage up to the start of the fade.
PSOut PSFarFadePbrTexN(PSInTexN In, bool is_front_face : SV_IsFrontFace)
{
	ClipFarFadeOpaque(In.ws_vert);
	return PSForwardPbrTexN(In, is_front_face);
}

// Collect fading multi-UV PBR coverage after applying the material's alpha mask.
void PSFarFadePbrTexNAlphaCollect(PSInTexN In, bool is_front_face : SV_IsFrontFace)
{
	// Resolve optional texture-coordinate lanes before storing the final PBR alpha attributes.
	ClipFarFadeCollect(In.ws_vert);
	PSIn base = ToPSIn(In);
	float4 diff = PSForwardPbrImpl(In, is_front_face).diff;
	float3 normal = ResolvePbrMaterialWorldNormal(base, is_front_face, PbrSlotUV(In, g_pbr.normal_texcoord, g_pbr.normal_uv_transform));
	CollectAlphaLayer(base, ApplyFarFadeAlpha(In.ws_vert, diff), AlphaRtAttributesFromNormal(diff, normal, g_nugget.env_reflectivity));
}

// Keep reflection attributes only for the surviving depth-writing multi-UV PBR coverage.
PSReflectionOut PSFarFadePbrTexNReflectionAttrs(PSInTexN In, bool is_front_face : SV_IsFrontFace)
{
	ClipFarFadeOpaque(In.ws_vert);
	return PSForwardPbrTexNReflectionAttrs(In, is_front_face);
}
