//*********************************************
// View 3d
//  Copyright (c) Rylogic Ltd 2022
//*********************************************
// Shader for forward rendering. Simple-material entry points are generated by 'pr/view3d-12/shaders/forward_pixel.hlsli'.
#ifndef PR_VIEW3D_SHADER_FORWARD_HLSL
#define PR_VIEW3D_SHADER_FORWARD_HLSL
#include "view3d-12/src/shaders/hlsl/types.hlsli"
#include "view3d-12/src/shaders/hlsl/forward/forward_cbuf.hlsli"
#include "view3d-12/src/shaders/hlsl/utility/surface_colour.hlsli"

static const int AlphaModeOpaque = 0;
static const int AlphaModeMask = 1;
static const int AlphaModeBlend = 2;

// Constant buffers
ConstantBuffer<CBufFrame> g_frame : register(b0);
ConstantBuffer<CBufElement> g_element : register(b1);
ConstantBuffer<CBufFade> g_fade: register(b2);
ConstantBuffer<CBufPbrSurface> g_pbr : register(b4);

// The render step's per-element constants, selected by the draw's element index
StructuredBuffer<ElementConstants> g_elements : register(t17);
static const ElementConstants g_nugget = g_elements[g_element.index];

// Textures /w samplers
Texture2D<float4> g_base_texture :register(t0);
SamplerState      g_base_sampler :register(s0);

// Environment map
TextureCube<float4> g_envmap_texture :register(t1);
SamplerState        g_envmap_sampler :register(s1);

// The previous environment map, which 'g_envmap_texture' fades in over (see 'g_frame.env_map.blend')
TextureCube<float4> g_envmap_prev_texture :register(t13);

// Distances from the current environment map's capture centre, stored as 'd / (d + S)' (see 'g_frame.env_map.centre')
TextureCube<float> g_envmap_distance :register(t21);

// Shadow atlas. The regions of the atlas are described by the shadow views in 'g_shadow_views'.
Texture2D<float> g_shadow_atlas         :register(t2);
SamplerComparisonState g_shadow_sampler :register(s2);

// Projected textures
Texture2D<float4> g_proj_texture[MaxProjectedTextures] :register(t3);
SamplerState      g_proj_sampler[MaxProjectedTextures] :register(s3);

// PBR material texture slots.
Texture2D<float4> g_metallic_texture  :register(t4);
Texture2D<float4> g_roughness_texture :register(t5);

// Opaque depth
Texture2DMS<float> g_opaque_depth : register(t6);

// PBR material texture slots continued after the shared forward resources.
Texture2D<float4> g_emissive_texture  :register(t7);
StructuredBuffer<float2> g_tex1 :register(t8);
StructuredBuffer<float2> g_tex2 :register(t9);
StructuredBuffer<float2> g_tex3 :register(t10);
StructuredBuffer<float2> g_tex4 :register(t11);
Texture2D<float4> g_normal_texture    :register(t12);
SamplerState      g_metallic_sampler  :register(s4);
SamplerState      g_roughness_sampler :register(s5);
SamplerState      g_emissive_sampler  :register(s6);
SamplerState      g_normal_sampler    :register(s7);

// The frame's world space lights. The count is in 'g_frame.light_info.x'.
StructuredBuffer<Light> g_lights :register(t15);

// The frame's shadow views. Lights with shadows refer to their views by index.
StructuredBuffer<ShadowView> g_shadow_views :register(t16);

// Alpha sorting
RasterizerOrderedTexture2D<uint4> g_alpha_colour :register(u0);
RasterizerOrderedTexture2D<uint4> g_alpha_depth  :register(u1);
RasterizerOrderedTexture2D<uint4> g_alpha_rt_attrs :register(u2);

#include "view3d-12/src/shaders/hlsl/forward/kbuffer.hlsli"
#include "view3d-12/src/shaders/hlsl/shadow/shadow_cast.hlsli"

// Lights are shadowed by the shadow atlas
float SampleLightShadow(Light light, float4 ws_pos, float4 ws_norm)
{
	// Shadow fading is measured along the camera's view direction (-Z)
	float view_depth = dot(g_frame.cam.c2w[3].xyz - ws_pos.xyz, g_frame.cam.c2w[2].xyz);
	return ShadowVisibility(g_shadow_atlas, g_shadow_sampler, g_shadow_views, light, ws_pos, ws_norm, view_depth);
}

#include "view3d-12/src/shaders/hlsl/lighting/phong_lighting.hlsli"
#include "view3d-12/src/shaders/hlsl/lighting/pbr.hlsli"
#include "view3d-12/src/shaders/hlsl/ray_tracing/ray_tracing.hlsli"
#include "view3d-12/src/shaders/hlsl/utility/colour_space.hlsli"
#include "view3d-12/src/shaders/hlsl/utility/env_map.hlsli"
#include "view3d-12/src/shaders/hlsl/forward/procedural_surface.hlsli"
#include "pr/hlsl/camera.hlsli"

// PS output format
struct PSOut
{
	float4 diff :SV_TARGET;
};
struct PSReflectionOut
{
	float4 diff :SV_TARGET0;
	float4 reflection_attrs :SV_TARGET1;
};

// Return the common pixel-shader input fields from a standard pixel-shader input.
PSIn ToPSIn(PSIn In)
{
	return In;
}

// Return the common pixel-shader input fields from an optional texture-coordinate input.
PSIn ToPSIn(PSInTexN In)
{
	PSIn Out = (PSIn)0;
	Out.ss_vert = In.ss_vert;
	Out.ws_vert = In.ws_vert;
	Out.ws_norm = In.ws_norm;
	Out.diff = In.diff;
	Out.tex0 = In.tex0;
	Out.idx0 = In.idx0;
	return Out;
}

// Return the transformed texture-coordinate value for a shader lane.
float2 PbrTextureUV(PSIn In, int texcoord)
{
	return In.tex0;
}

// Return the transformed texture-coordinate value for a shader lane.
float2 PbrTextureUV(PSInTexN In, int texcoord)
{
	switch (texcoord)
	{
		case 1: return In.tex1;
		case 2: return In.tex2;
		case 3: return In.tex3;
		case 4: return In.tex4;
		default: return In.tex0;
	}
}

// Return one channel from a texture sample using the channel index stored in the material constants.
float SelectTextureChannel(float4 sample, int channel)
{
	return
		channel == 0 ? sample.r :
		channel == 1 ? sample.g :
		channel == 2 ? sample.b :
		channel == 3 ? sample.a :
		sample.r;
}

// Apply a material texture-coordinate transform before sampling a texture slot.
float2 TransformPbrUV(float2 uv, TexXForm transform)
{
	float3 uv1 = float3(uv, 1);
	return float2(dot(uv1, transform.m_x.xyz), dot(uv1, transform.m_y.xyz));
}

// Return the transformed texture-coordinate value for a material texture slot.
template <typename TIn>
float2 PbrSlotUV(TIn In, int texcoord, TexXForm transform)
{
	return TransformPbrUV(PbrTextureUV(In, texcoord), transform);
}

// Return the world-space surface normal used by the forward material path.
float4 ResolveWorldNormal(PSIn In, bool is_front_face)
{
	if (!HasNormals(g_nugget.flags))
		return float4(0, 0, 0, 0);

	float4 norm =
		dot(In.ws_norm, In.ws_norm) != 0 ? normalize(In.ws_norm) :
		g_frame.light_info.x != 0 ? -LightDirectionAt(g_lights[0], In.ws_vert) :
		float4(0, 0, 0, 0);

	if (TwoSided(g_nugget.flags) && !is_front_face)
		norm = -norm;

	return norm;
}

// Apply the material normal-map sample to a world-space geometric normal.
float3 PerturbWorldNormal(PSIn In, float3 normal, float2 normal_uv)
{
	float2 map_xy = g_normal_texture.Sample(g_normal_sampler, normal_uv).xy * 2.0f - 1.0f;
	map_xy *= g_pbr.normal_scale;
	float3 map_normal = normalize(float3(map_xy, sqrt(saturate(1.0f - dot(map_xy, map_xy)))));

	float3 dp1 = ddx(In.ws_vert.xyz);
	float3 dp2 = ddy(In.ws_vert.xyz);
	float2 duv1 = ddx(normal_uv);
	float2 duv2 = ddy(normal_uv);
	float3 dp2_perp = cross(dp2, normal);
	float3 dp1_perp = cross(normal, dp1);
	float3 tangent = dp2_perp * duv1.x + dp1_perp * duv2.x;
	float3 bitangent = dp2_perp * duv1.y + dp1_perp * duv2.y;
	float frame_len = max(dot(tangent, tangent), dot(bitangent, bitangent));
	if (frame_len < TINY)
		return normal;

	float inv_frame_len = rsqrt(frame_len);
	return normalize(
		tangent * (map_normal.x * inv_frame_len) +
		bitangent * (map_normal.y * inv_frame_len) +
		normal * map_normal.z);
}

// Return the world-space normal from a model-space normal map.
// The map stores model-space X/Y in [0,1]; Z is rebuilt as non-negative, so the map can only describe normals in the model +Z hemisphere.
float3 ModelSpaceMapWorldNormal(bool is_front_face, float2 normal_uv)
{
	// Rebuild Z after scaling X/Y. Filtered mips shorten X/Y, which the rebuild keeps unit length.
	float2 map_xy = g_normal_texture.Sample(g_normal_sampler, normal_uv).xy * 2.0f - 1.0f;
	map_xy *= g_pbr.normal_scale;
	float3 ms_normal = float3(map_xy, sqrt(saturate(1.0f - dot(map_xy, map_xy))));

	// Transform with the nugget normal transform, then flip back faces like the geometric normal.
	float3 normal = normalize(mul(float4(ms_normal, 0), g_nugget.n2w).xyz);
	if (TwoSided(g_nugget.flags) && !is_front_face)
		normal = -normal;

	return normal;
}

// Return the PBR surface normal after applying any usable normal-map texture.
float3 ResolvePbrWorldNormal(PSIn In, bool is_front_face, float2 normal_uv)
{
	// A model-space map replaces the interpolated vertex normal completely.
	if (AnySet(g_pbr.texture_flags, PbrTextureFlag_HasNormalMap) && AnySet(g_pbr.texture_flags, PbrTextureFlag_NormalMapModel) && HasNormals(g_nugget.flags))
		return ModelSpaceMapWorldNormal(is_front_face, normal_uv);

	float3 normal = ResolveWorldNormal(In, is_front_face).xyz;
	if (dot(normal, normal) == 0.0f)
		return normal;

	normal = normalize(normal);
	if (AnySet(g_pbr.texture_flags, PbrTextureFlag_HasNormalMap))
		normal = PerturbWorldNormal(In, normal, normal_uv);

	return normal;
}

// Return the final world normal after texture and UV-free procedural perturbations.
float3 ResolvePbrMaterialWorldNormal(PSIn In, bool is_front_face, float2 normal_uv)
{
	// Resolve the authored normal source before applying the optional UV-free height field.
	float3 normal = ResolvePbrWorldNormal(In, is_front_face, normal_uv);
	if (dot(normal, normal) == 0.0f || g_pbr.procedural_params0.x == 0.0f)
		return normal;

	ProceduralSurfaceSample procedural = EvaluateProceduralSurface(In.ws_vert);
	return ProceduralWorldNormal(In, normal, procedural.height);
}

// Forward VS
PSIn VSForward(VSIn In)
{
	PSIn Out = (PSIn)0;

	// Transform
	float4 os_vert = mul(In.vert, g_nugget.m2o);
	
	Out.ws_vert = mul(os_vert, g_nugget.o2w);
	Out.ws_norm = mul(In.norm, g_nugget.n2w);
	Out.ss_vert = mul(os_vert, g_nugget.o2s);

	// Tinting
	Out.diff = g_nugget.tint;

	// Per Vertex colour
	Out.diff = In.diff * Out.diff;

	// Texture2D (with transform)
	Out.tex0 = mul(float4(In.tex0, 0, 1), g_nugget.tex2surf0).xy;

	// Copy the source instance index
	Out.idx0 = In.idx0;
	
	return Out;
}

// Forward VS variant that interpolates optional texture-coordinate lanes for PBR material textures.
PSInTexN VSForwardTexN(VSIn In, uint vertex_id : SV_VertexID)
{
	PSIn base = VSForward(In);

	PSInTexN Out = (PSInTexN)0;
	Out.ss_vert = base.ss_vert;
	Out.ws_vert = base.ws_vert;
	Out.ws_norm = base.ws_norm;
	Out.diff = base.diff;
	Out.tex0 = base.tex0;
	Out.idx0 = base.idx0;

	// Optional streams follow the model vertex-buffer order. SV_VertexID is already the model-buffer index for both indexed and non-indexed draws.
	if (g_pbr.texcoord_count > 0)
		Out.tex1 = g_tex1[vertex_id];

	if (g_pbr.texcoord_count > 1)
		Out.tex2 = g_tex2[vertex_id];

	if (g_pbr.texcoord_count > 2)
		Out.tex3 = g_tex3[vertex_id];

	if (g_pbr.texcoord_count > 3)
		Out.tex4 = g_tex4[vertex_id];

	return Out;
}

// Mean square slope of surface detail too fine for the interpolated normal to show. Pixel-shader variants that know it set it before shading.
// The stock shaders leave it at zero, so their reflections stay mirror-sharp.
static float g_unresolved_slope_variance = 0.0f;

// Shade one simple-material fragment, returning the linear colour before output dithering.
PSOut ForwardShade(PSIn In, bool is_front_face)
{
	// Notes:
	//  - 'ss_vert:SV_Position' in the pixel shader already has x,y,z divided by w (w unchanged)
	//  - Models without normals can still use 'HasNormals' as true. For this case, and normal to
	//    the light source is used.

	PSOut Out = (PSOut)0;

	// Tinting
	Out.diff = In.diff;

	// Transform
	if (HasNormals(g_nugget.flags))
	{
		// If the normal is (0,0,0), use a vector to the light source
		In.ws_norm = ResolveWorldNormal(In, is_front_face);
	}

	// Texture2D (with transform)
	if (HasTex0(g_nugget.flags))
	{
		if (EnvMapProj(g_nugget.flags))
		{
			float3 dir = mul(In.ws_vert, g_nugget.tex2surf0).xyz;
			Out.diff = SampleEnvMap(dir, dir, ddx(dir), ddy(dir));
		}
		else
		{
			float4 texel = g_base_texture.Sample(g_base_sampler, In.tex0);
			Out.diff = texel * Out.diff;
		}
	}

	// Override the completed surface RGB before reflections and lighting; leave opacity untouched.
	Out.diff = SurfaceColourBlend(Out.diff, g_nugget.colour_blend);

	// Env Map
	if (HasEnvMap(g_nugget.flags) && HasNormals(g_nugget.flags))
		Out.diff = EnvironmentMap(In.ws_vert, In.ws_norm, g_frame.cam.c2w[3], In.ss_vert.xy, Out.diff, g_unresolved_slope_variance);

	// Lighting, including shadows
	if (HasNormals(g_nugget.flags))
		Out.diff = Illuminate(g_lights, g_frame.light_info.x, g_frame.ambient.rgb, In.ws_vert, In.ws_norm, g_frame.cam.c2w[3], Out.diff);

	// If not alpha blending, clip alpha pixels
	if (!HasAlpha(g_nugget.flags))
		clip(Out.diff.a - 0.5);

	return Out;
}

// Dither a final colour written directly to the 8-bit render target. Only the RGB channels are dithered.
float4 DitherOutput(float4 colour, float4 ss_vert)
{
	return float4(DitherSrgb8(colour.rgb, uint2(ss_vert.xy), g_frame.output.x, 0), colour.a);
}

// Direct-lighting PBR pixel shader path using the supplied UV coordinates for each texture slot.
PSOut PSForwardPbrSampledUV(PSIn In, bool is_front_face, float2 base_uv, float2 metallic_uv, float2 roughness_uv, float2 emissive_uv, float2 normal_uv)
{
	PSOut Out = (PSOut)0;

	// Resolve the scalar and texture-backed material inputs into a linear base colour.
	float4 base_colour = g_pbr.base_colour * In.diff;
	if (AnySet(g_pbr.texture_flags, PbrTextureFlag_HasBaseColourMap))
	{
		float4 tex_colour = g_base_texture.Sample(g_base_sampler, base_uv);
		if (AnySet(g_pbr.texture_flags, PbrTextureFlag_BaseColourSrgb))
			tex_colour = SrgbToLinear(tex_colour);

		base_colour *= tex_colour;
	}

	// Override the completed linear surface colour before lighting and leave the material alpha mode unchanged.
	base_colour = SurfaceColourBlend(base_colour, g_nugget.colour_blend);

	// Apply the material alpha mode before lighting so masked surfaces can discard early.
	float alpha = base_colour.a;
	if (g_pbr.alpha_mode == AlphaModeMask)
		clip(alpha - g_pbr.alpha_cutoff);
	else if (g_pbr.alpha_mode == AlphaModeOpaque)
		alpha = 1.0f;

	// Convert material parameters to the ranges expected by the PBR lighting equations.
	float3 albedo = saturate(base_colour.rgb);
	float metallic = saturate(g_pbr.metallic);
	float roughness = clamp(g_pbr.roughness, 0.04f, 1.0f);
	float3 emissive = g_pbr.emissive.rgb;
	if (AnySet(g_pbr.texture_flags, PbrTextureFlag_HasMetallicMap))
		metallic *= SelectTextureChannel(g_metallic_texture.Sample(g_metallic_sampler, metallic_uv), g_pbr.metallic_channel);
	if (AnySet(g_pbr.texture_flags, PbrTextureFlag_HasRoughnessMap))
		roughness *= SelectTextureChannel(g_roughness_texture.Sample(g_roughness_sampler, roughness_uv), g_pbr.roughness_channel);
	if (AnySet(g_pbr.texture_flags, PbrTextureFlag_HasEmissiveMap))
	{
		float4 emissive_tex = g_emissive_texture.Sample(g_emissive_sampler, emissive_uv);
		if (AnySet(g_pbr.texture_flags, PbrTextureFlag_EmissiveSrgb))
			emissive_tex = SrgbToLinear(emissive_tex);

		emissive *= emissive_tex.rgb;
	}

	metallic = saturate(metallic);
	roughness = clamp(roughness, 0.04f, 1.0f);

	// Procedural surfaces modulate the completed albedo and replace roughness without requiring UV or tangent data.
	ProceduralSurfaceSample procedural = (ProceduralSurfaceSample)0;
	if (g_pbr.procedural_params0.x != 0.0f)
	{
		procedural = EvaluateProceduralSurface(In.ws_vert);
		albedo *= procedural.albedo;
		roughness = clamp(procedural.roughness, 0.04f, 1.0f);
	}

	// Without a usable normal there is no surface orientation, so leave the material effectively unlit.
	if (!HasNormals(g_nugget.flags))
	{
		Out.diff = float4(saturate(albedo + emissive), alpha);
		return Out;
	}

	float3 normal = ResolvePbrWorldNormal(In, is_front_face, normal_uv);
	if (dot(normal, normal) == 0.0f)
	{
		Out.diff = float4(saturate(albedo + emissive), alpha);
		return Out;
	}
	if (g_pbr.procedural_params0.x != 0.0f)
		normal = ProceduralWorldNormal(In, normal, procedural.height);

	// Evaluate direct PBR lighting using the shared PBR material lighting helper.
	float3 view = normalize(g_frame.cam.c2w[3].xyz - In.ws_vert.xyz);
	float3 colour = PbrIlluminate(g_lights, g_frame.light_info.x, g_frame.ambient.rgb, In.ws_vert.xyz, normal, view, albedo, metallic, roughness, emissive);

	// Add specular reflection of the environment map. Rougher surfaces sample blurrier mips, and the Fresnel term keeps dielectrics mostly
	// non-reflective except at grazing angles. 'env_reflectivity' scales the whole term so reflections remain opt-in per instance.
	if (HasEnvMap(g_nugget.flags))
	{
		uint env_w, env_h, env_mips;
		g_envmap_texture.GetDimensions(0, env_w, env_h, env_mips);
		float lod = roughness * (env_mips - 1);

		float3 f0 = lerp(0.04f, albedo, metallic);
		float n_dot_v = saturate(dot(normal, view));
		float3 fresnel = f0 + (max(1.0f - roughness, f0) - f0) * pow(1.0f - n_dot_v, 5.0f);
		float importance = max(max(fresnel.r, fresnel.g), fresnel.b) * saturate(g_nugget.env_reflectivity);

		float3 r, r_prev;
		EnvMapDirections(In.ws_vert.xyz, reflect(-view, normal), In.ss_vert.xy, importance, lod, r, r_prev);
		float3 env = SampleEnvMapLevel(r, r_prev, lod).rgb;
		colour += env * fresnel * g_nugget.env_reflectivity;
	}

	Out.diff = float4(saturate(colour), alpha);
	return Out;
}

// Direct-lighting PBR pixel shader path shared by concrete fast-path and optional texture-coordinate entry points.
template <typename TIn>
PSOut PSForwardPbrImpl(TIn In, bool is_front_face)
{
	return PSForwardPbrSampledUV(
		ToPSIn(In),
		is_front_face,
		PbrSlotUV(In, g_pbr.base_colour_texcoord, g_pbr.base_colour_uv_transform),
		PbrSlotUV(In, g_pbr.metallic_texcoord, g_pbr.metallic_uv_transform),
		PbrSlotUV(In, g_pbr.roughness_texcoord, g_pbr.roughness_uv_transform),
		PbrSlotUV(In, g_pbr.emissive_texcoord, g_pbr.emissive_uv_transform),
		PbrSlotUV(In, g_pbr.normal_texcoord, g_pbr.normal_uv_transform));
}

// Direct-lighting PBR pixel shader path with optional texture-coordinate lanes.
PSOut PSForwardPbrTexN(PSInTexN In, bool is_front_face : SV_IsFrontFace)
{
	PSOut Out = PSForwardPbrImpl(In, is_front_face);
	Out.diff = DitherOutput(Out.diff, In.ss_vert);
	return Out;
}

// Collect one transparent fragment into the forward alpha K-buffer.
void CollectAlphaLayer(PSIn In, float4 diff, uint rt_attrs)
{
	// Fade transparent layers with view depth so they vanish into the background with the opaque scene. See scene/far_clip_fade.md.
	float view_z = -mul(In.ws_vert, g_frame.cam.w2c).z;
	if (g_frame.far_fade.z != 0.0f)
		diff.a *= 1.0f - smoothstep(g_frame.far_fade.x, g_frame.far_fade.y, view_z);

	// Discard fully transparent fragments before accessing the ordered layer buffers.
	clip(diff.a - (1.0f / 255.0f));

	// Reject transparent fragments hidden behind the opaque pass.
	uint2 pix = uint2(In.ss_vert.xy);
	uint width, height, sample_count;
	g_opaque_depth.GetDimensions(width, height, sample_count);

	// Reversed depth: the nearest sample has the greatest depth. Start at the far plane (0).
	float opaque_depth = 0.0f;
	for (uint sample = 0; sample != sample_count; ++sample)
		opaque_depth = max(opaque_depth, g_opaque_depth.Load(pix, sample));
	if (In.ss_vert.z <= opaque_depth)
		discard;

	// Pack view-space depth, colour, and optional RT side-buffer metadata for later resolve.
	uint depth = PackDepthKey(view_z, ClipPlanes(g_frame.cam.c2s), uint(g_nugget.flags.w));
	uint colour = PackSrgbRGBA8(diff, DitherOffsetSrgb8(pix, g_frame.output.x, 1));

	// Insert the transparent layer into the rasterizer-ordered K-buffer.
	uint4 alpha_colour = g_alpha_colour[pix];
	uint4 alpha_depth = g_alpha_depth[pix];
	uint4 alpha_rt_attrs = g_alpha_rt_attrs[pix];
	InsertKBufferLayer(alpha_colour, alpha_depth, alpha_rt_attrs, colour, depth, rt_attrs);
	g_alpha_colour[pix] = alpha_colour;
	g_alpha_depth[pix] = alpha_depth;
	g_alpha_rt_attrs[pix] = alpha_rt_attrs;
}

// Collect transparent PBR fragments with optional texture-coordinate lanes into the alpha K-buffer.
void PSForwardPbrTexNAlphaCollect(PSInTexN In, bool is_front_face : SV_IsFrontFace)
{
	// Resolve optional texture-coordinate lanes before storing the final PBR alpha attributes.
	PSIn base = ToPSIn(In);
	float4 diff = PSForwardPbrImpl(In, is_front_face).diff;
	float3 normal = ResolvePbrMaterialWorldNormal(base, is_front_face, PbrSlotUV(In, g_pbr.normal_texcoord, g_pbr.normal_uv_transform));
	CollectAlphaLayer(base, diff, AlphaRtAttributesFromNormal(diff, normal, g_nugget.env_reflectivity));
}

// PBR forward pass with optional texture-coordinate lanes that also writes reflection attributes for RT reflections.
PSReflectionOut PSForwardPbrTexNReflectionAttrs(PSInTexN In, bool is_front_face : SV_IsFrontFace)
{
	PSIn base = ToPSIn(In);
	PSReflectionOut Out = (PSReflectionOut)0;
	Out.diff = PSForwardPbrImpl(In, is_front_face).diff;
	Out.reflection_attrs = PbrReflectionAttributes(
		base,
		Out.diff,
		PbrSlotUV(In, g_pbr.metallic_texcoord, g_pbr.metallic_uv_transform),
		ResolvePbrMaterialWorldNormal(base, is_front_face, PbrSlotUV(In, g_pbr.normal_texcoord, g_pbr.normal_uv_transform)));
	Out.diff = DitherOutput(Out.diff, In.ss_vert);
	return Out;
}

// Forward radial fade pass.
PSOut PSForwardRadialFade(PSIn In, bool is_front_face : SV_IsFrontFace)
{
	PSOut Out = ForwardShade(In, is_front_face);

	// Fade pixels radially from 'centre'
	float4 centre = any(g_fade.fade_centre) ? g_fade.fade_centre : g_frame.cam.c2w[3];
	float4 radial = In.ws_vert - centre;
	float radius =
		g_fade.fade_type == 0 ? length(radial) : // Spherical
		g_fade.fade_type == 1 ? length(radial - dot(radial, g_frame.cam.c2w[1]) * g_frame.cam.c2w[1]) : // Cylindrical
		0;

	// Lerp to alpha = 0 based on distance
	float frac = smoothstep(g_fade.fade_radius[0], g_fade.fade_radius[1], radius);
	Out.diff.a = lerp(Out.diff.a, 0, frac);
	Out.diff = DitherOutput(Out.diff, In.ss_vert);
	return Out;
}

#endif
