<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>$(PrimaryTarget)</TargetFrameworks>
		<RootNamespace>Lab.UI</RootNamespace>
		<AssemblyName>Lab</AssemblyName>
		<UseWPF>true</UseWPF>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<!-- Assembly properties -->
	<PropertyGroup>
		<Authors>P Ryland</Authors>
		<Company>Rylogic</Company>
		<Description>Signal analysis laboratory.</Description>
		<Copyright>Copyright (c) Rylogic 2026</Copyright>
		<Version>1.0.0</Version>
		<FileVersion>1.0.0</FileVersion>
		<AssemblyVersion>1.0.0</AssemblyVersion>
	</PropertyGroup>

	<!-- Code -->
	<ItemGroup>
		<ApplicationDefinition Include="src\App.xaml" />
	</ItemGroup>

	<!-- References -->
	<ItemGroup>
		<ProjectReference Include="$(RylogicRoot)projects\rylogic\Rylogic.Core\Rylogic.Core.csproj" />
		<ProjectReference Include="$(RylogicRoot)projects\rylogic\Rylogic.Gui.WPF\Rylogic.Gui.WPF.csproj" />
		<ProjectReference Include="$(RylogicRoot)projects\rylogic\Rylogic.Gfx\Rylogic.Gfx.csproj" />
		<ProjectReference Include="$(RylogicRoot)projects\rylogic\Rylogic.Gfx.WPF\Rylogic.Gfx.WPF.csproj" />
		<ProjectReference Include="..\Lab.Model\Lab.Model.csproj" />
	</ItemGroup>

	<!-- Targets -->
	<Import Project="$(TargetsPath)view3d-12.targets" />
	<Import Project="$(TargetsPath)sqlite3.targets" />

</Project>
