//*********************************************
// View3d-12 Tests
//  Copyright (C) Rylogic Ltd 2026
//*********************************************
// Demos of procedural geometry generated by custom vertex shaders.
#include <array>
#include <cmath>
#include <cstdint>
#include <format>
#include <limits>
#include <stdexcept>
#include <vector>
#include "pr/gui/wingui.h"
#include "pr/view3d-12/view3d-dll.h"
#include "demo.h"
#include "controls_panel.h"

namespace view3d_test
{
	namespace compiled
	{
		#include "wave_grid.h"
	}

	namespace
	{
		namespace api = pr::view3d;

		// Must match 'WaveGridConstants' in wave_grid.hlsl. Procedural constants are always 'ConstantsSize' bytes.
		struct WaveGridConstants
		{
			api::Vec4 m_wave;      // x = amplitude, y = spatial frequency (radians per unit), z = angular speed (radians per second), w = time (seconds)
			api::Vec4 m_grid;      // x = vertices per side, y = side length
			api::Vec4 m_colour_lo; // Colour at the wave troughs
			api::Vec4 m_colour_hi; // Colour at the wave crests
			std::array<unsigned char, api::ProceduralBinding::ConstantsSize - 4 * sizeof(api::Vec4)> m_padding;
		};
		static_assert(sizeof(WaveGridConstants) == api::ProceduralBinding::ConstantsSize);

		// A grid whose vertices are computed each frame by a vertex shader, from the vertex index and a few animation constants
		struct WaveGridDemo :IDemo
		{
			static constexpr int GridSize = 128;
			static constexpr float SideLength = 20.0f;
			static constexpr float MaxAmplitude = 2.0f;

			DemoContext m_ctx;
			WaveGridConstants m_constants;
			api::ShaderPtr m_shader; // Declared before 'm_scene' so the shader outlives the object that uses it
			demo::SceneObjects m_scene;
			api::Object m_grid;
			bool m_paused;

			explicit WaveGridDemo(DemoContext const& ctx)
				: m_ctx(ctx)
				, m_constants({
					.m_wave = {0.8f, 0.6f, 1.5f, 0.0f},
					.m_grid = {static_cast<float>(GridSize), SideLength, 0, 0},
					.m_colour_lo = {0.05f, 0.15f, 0.45f, 1},
					.m_colour_hi = {0.75f, 0.9f, 1.0f, 1},
					.m_padding = {},
				})
				, m_shader()
				, m_scene(ctx.m_window)
				, m_grid()
				, m_paused(false)
			{
				// The shader keeps a copy of the initial constants. 'Step' replaces them through the object each frame.
				auto options = api::ShaderOptions{
					.m_struct_size = sizeof(api::ShaderOptions),
					.m_version = api::ShaderOptions::CurrentVersion,
					.m_stage = api::EShaderStage::Vertex,
					.m_bytecode = compiled::wave_grid,
					.m_bytecode_size = sizeof(compiled::wave_grid),
					.m_dbg_name = "WaveGrid",
					.m_procedural = {
						.m_rdr_step = api::ERenderStep::ForwardRender,
						.m_constants = &m_constants,
						.m_constants_size = sizeof(m_constants),
					},
				};
				m_shader.reset(View3D_ShaderCreate(options));
				if (!m_shader)
					throw std::runtime_error("Failed to create the wave grid shader");

				// Index the logical vertices as two triangles per grid cell. The shader generates the vertex data, so the
				// model only needs one placeholder vertex. The bounding box must contain the surface at the maximum amplitude.
				auto indices = std::vector<uint32_t>{};
				indices.reserve(6 * (GridSize - 1) * (GridSize - 1));
				for (uint32_t j = 0; j != GridSize - 1; ++j)
				{
					// One row of cells. Vertices are numbered row by row.
					for (uint32_t i = 0; i != GridSize - 1; ++i)
					{
						auto v00 = j * GridSize + i;
						auto v10 = v00 + 1;
						auto v01 = v00 + GridSize;
						auto v11 = v01 + 1;
						indices.insert(indices.end(), {v00, v10, v11, v00, v11, v01});
					}
				}
				auto nan = std::numeric_limits<float>::quiet_NaN();
				auto placeholder = api::Vertex{{nan, nan, nan, nan}, {nan, nan, nan, nan}, {nan, nan}, 0x00010203, 0};
				auto object_options = api::ObjectCreateOptions{
					.m_struct_size = sizeof(api::ObjectCreateOptions),
					.m_version = api::ObjectCreateOptions::CurrentVersion,
					.m_vertex_source = api::EVertexSource::ProceduralVertexId,
					.m_vcount_logical = GridSize * GridSize,
					.m_bbox = {{0, 0, 0, 1}, {SideLength * 0.5f, SideLength * 0.5f, MaxAmplitude, 0}},
				};
				auto nugget = api::Nugget{};
				nugget.m_topo = api::ETopo::TriList;
				nugget.m_geom = static_cast<api::EGeom>(static_cast<int>(api::EGeom::Vert) | static_cast<int>(api::EGeom::Colr) | static_cast<int>(api::EGeom::Norm) | static_cast<int>(api::EGeom::Tex0));
				nugget.m_v1 = 1;
				nugget.m_i1 = static_cast<int>(indices.size());
				nugget.m_tint = 0xFFFFFFFF;
				nugget.m_cull_mode = api::ECullMode::None;
				nugget.m_shaders[0] = {m_shader.get(), api::ERenderStep::ForwardRender, 0};
				m_grid = View3D_ObjectCreateU32("wave_grid", 0xFFFFFFFF, 1, static_cast<int>(indices.size()), 1, &placeholder, indices.data(), &nugget, object_options, GUID{});
				if (m_grid == nullptr)
					throw std::runtime_error("Failed to create the wave grid object");

				m_scene.Add(m_grid);
				View3D_CameraPositionSet(ctx.m_window, {0, -22, 12, 1}, {0, 0, 0, 1}, {0, 0, 1, 0});

				// Wave controls
				auto& ui = ctx.m_controls;
				ui.AddLabel(L"The surface is generated by the vertex shader. Check that the lighting follows the waves.");
				ui.AddSlider(L"Amplitude", 0, MaxAmplitude, m_constants.m_wave.x, [this](float v)
				{
					m_constants.m_wave.x = v;
				});
				ui.AddSlider(L"Frequency", 0.1f, 2.0f, m_constants.m_wave.y, [this](float v)
				{
					m_constants.m_wave.y = v;
				});
				ui.AddSlider(L"Speed", 0, 5, m_constants.m_wave.z, [this](float v)
				{
					m_constants.m_wave.z = v;
				});
				ui.AddCheckBox(L"Paused", m_paused, [this](bool v)
				{
					m_paused = v;
				});
			}

			// Advance the wave and upload the constants
			void Step(double dt) override
			{
				// Upload every frame so slider changes apply while paused
				if (!m_paused)
					m_constants.m_wave.w += static_cast<float>(dt);

				View3D_ObjectProceduralConstantsSet(m_grid, &m_constants, sizeof(m_constants));
			}
		};
	}

	// Demo factories
	std::unique_ptr<IDemo> CreateWaveGridDemo(DemoContext const& ctx)
	{
		return std::make_unique<WaveGridDemo>(ctx);
	}
}
