//*********************************************
// Physics Engine
//  Copyright (C) Rylogic Ltd 2026
//*********************************************
// Forward declaration for GpuCollisionDetector (pimpl pattern).
// The full definition lives in gpu_collision_detector.cpp and includes view3d-12 headers.
// This header is safe to include from any physics public header.
#pragma once
#include "pr/physics/forward.h"
#include "src/compute/physics_types.h"
#include "src/utility/gpu.h"

namespace pr::physics
{
	struct GpuCollisionDetector
	{
		using CollisionShaders = std::array<ComputeStep, COLLISION_BIN_COUNT>;

		Gpu& m_gpu;                                  // Lightweight D3D12 wrapper (device + command queue)
		EngineConfig const& m_config;                // Engine configuration parameters
		ComputeStep m_cs_clear_bins;                 // Root signature + PSO for clearing collision bin counters
		ComputeStep m_cs_bin_pairs;                  // Root signature + PSO for classifying broadphase pairs into bins
		ComputeStep m_cs_build_bin_dispatch;         // Root signature + PSO for building per-bin indirect dispatch args
		CollisionShaders m_cs_collide_bins;          // Root signatures + PSOs for exact pair-type collide shaders
		ComputeStep m_cs_calc_dispatch;              // Root signature + PSO for calculating the dispatch size of the resolve shader
		D3DPtr<ID3D12CommandSignature> m_cmd_sig;    // Command signature for indirect dispatch of the collision shader
		D3DPtr<ID3D12Resource> m_r_shapes;           // GPU buffer: StructuredBuffer<GpuShape>
		D3DPtr<ID3D12Resource> m_r_verts;            // GPU buffer: StructuredBuffer<float4>
		D3DPtr<ID3D12Resource> m_r_faces;            // GPU buffer: StructuredBuffer<GpuPolytopeFace>
		D3DPtr<ID3D12Resource> m_r_edges;            // GPU buffer: StructuredBuffer<GpuPolytopeEdge>
		D3DPtr<ID3D12Resource> m_r_contacts;         // GPU buffer: RWStructuredBuffer<GpuResolveContact>
		D3DPtr<ID3D12Resource> m_r_resolve_dispatch; // GPU buffer: RWStructuredBuffer<D3D12_DISPATCH_ARGUMENTS> for indirect dispatch of the resolve shader based on the number of contacts generated by CD
		D3DPtr<ID3D12Resource> m_r_bin_counts;       // GPU buffer: RWStructuredBuffer<uint> per exact pair-type bin
		D3DPtr<ID3D12Resource> m_r_bin_pair_indices; // GPU buffer: RWStructuredBuffer<uint> broadphase pair indices grouped by bin
		D3DPtr<ID3D12Resource> m_r_bin_dispatch;     // GPU buffer: RWStructuredBuffer<D3D12_DISPATCH_ARGUMENTS> per exact pair-type bin
		int m_max_contacts;
		int m_max_pairs;
		int m_max_shapes;
		int m_max_verts;
		int m_max_faces;
		int m_max_edges;

		explicit GpuCollisionDetector(Gpu& gpu, EngineConfig const& config);

		// Run collision detection on the GPU. Outputs GpuResolveContact directly.
		void DetectCollisions(GpuJob& job, int max_contacts, int max_pairs, D3DPtr<ID3D12Resource> dispatch, D3DPtr<ID3D12Resource> pairs, D3DPtr<ID3D12Resource> counters, ShapeCache const& shape_cache);
		void DetectCollisions(GpuJob& job, int max_contacts, int max_pairs, D3DPtr<ID3D12Resource> dispatch, D3DPtr<ID3D12Resource> pairs, D3DPtr<ID3D12Resource> counters, D3DPtr<ID3D12Resource> contacts, D3DPtr<ID3D12Resource> resolve_dispatch, ShapeCache const& shape_cache);

		// CPU-side testing: upload pairs, shapes, materials and read back contacts
		std::span<GpuResolveContact> DetectCollisions(GpuJob& job, std::span<GpuCollisionPair const> pairs, ShapeCache const& shape_cache, std::span<GpuResolveContact> out_contacts);

		// Read back the results of the collision detection
		std::span<GpuResolveContact> Readback(GpuJob& job, D3DPtr<ID3D12Resource> r_counters, std::span<GpuResolveContact> out_contacts);

		// Get the GPU resources
		D3DPtr<ID3D12Resource> Contacts() { return m_r_contacts; }
		D3DPtr<ID3D12Resource> ResolveDispatchArgs() { return m_r_resolve_dispatch; }

	private:

		// Compile the compute shaders
		void CompileShaders();

		// Resize the GPU buffers to support 'max_contacts' contact points, and the cached shape data.
		bool ResizeBuffers(CmdList& cmd_list, int max_contacts, int max_pairs, int max_shapes, int max_verts, int max_faces, int max_edges);
	};
}
