//*********************************************
// Physics Engine
//  Copyright (C) Rylogic Ltd 2026
//*********************************************
// Forward declaration for GpuCollisionDetector (pimpl pattern).
// The full definition lives in gpu_collision_detector.cpp and includes view3d-12 headers.
// This header is safe to include from any physics public header.
#pragma once
#include "pr/physics/forward.h"
#include "src/utility/gpu.h"

namespace pr::physics
{
	struct GpuCollisionDetector
	{
		Gpu& m_gpu;                                  // Lightweight D3D12 wrapper (device + command queue)
		ComputeStep m_cs_collide;                    // Root signature + PSO for the collide shader
		ComputeStep m_cs_calc_dispatch;              // Root signature + PSO for calculating the dispatch size of the resolve shader
		D3DPtr<ID3D12CommandSignature> m_cmd_sig;    // Command signature for indirect dispatch of the collision shader
		D3DPtr<ID3D12Resource> m_r_shapes;           // GPU buffer: StructuredBuffer<GpuShape>
		D3DPtr<ID3D12Resource> m_r_verts;            // GPU buffer: StructuredBuffer<float4>
		D3DPtr<ID3D12Resource> m_r_contacts;         // GPU buffer: RWStructuredBuffer<GpuResolveContact>
		D3DPtr<ID3D12Resource> m_r_resolve_dispatch; // GPU buffer: RWStructuredBuffer<D3D12_DISPATCH_ARGUMENTS> for indirect dispatch of the resolve shader based on the number of contacts generated by CD
		#if PR_COLLISION_DIAGNOSTICS
		D3DPtr<ID3D12Resource> m_r_diag;             // GPU buffer: RWStructuredBuffer<GpuPairDiag>
		#endif
		int m_max_contacts;
		int m_max_shapes;
		int m_max_verts;

		explicit GpuCollisionDetector(Gpu& gpu);

		// Run collision detection on the GPU. Outputs GpuResolveContact directly.
		void DetectCollisions(GpuJob& job, int max_contacts, D3DPtr<ID3D12Resource> dispatch, D3DPtr<ID3D12Resource> pairs, D3DPtr<ID3D12Resource> counters, ShapeCache const& shape_cache);

		// Read back the results of the collision detection
		std::tuple<std::span<GpuResolveContact>, std::span<GpuPairDiag>> Readback(GpuJob& job, D3DPtr<ID3D12Resource> r_counters, std::span<GpuResolveContact> out_contacts, std::span<GpuPairDiag> out_diag);

		// CPU-side testing: upload pairs, shapes, materials and read back contacts
		std::tuple<std::span<GpuResolveContact>, std::span<GpuPairDiag>> DetectCollisions(GpuJob& job, std::span<GpuCollisionPair const> pairs, ShapeCache const& shape_cache, std::span<GpuResolveContact> out_contacts, std::span<GpuPairDiag> out_diag);

		// Get the GPU resources
		D3DPtr<ID3D12Resource> Contacts() { return m_r_contacts; }
		D3DPtr<ID3D12Resource> ResolveDispatchArgs() { return m_r_resolve_dispatch; }

	private:

		// Compile the compute shaders
		void CompileShaders();

		// Resize the GPU buffers to support 'max_contacts' contact points, and 'max_shapes' shapes with 'max_verts' vertices.
		bool ResizeBuffers(CmdList& cmd_list, int max_contacts, int max_shapes, int max_verts);
	};
}
